server:
  port: 9000
  
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:adithyamr/personal-investment-tracker-config.git
          default-label: master
          clone-on-start: true
          force-pull: true
          search-paths:
          - '*api'
          ignoreLocalSshSettings: true
          hostKey: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          hostKeyAlgorithm: ecdsa-sha2-nistp256
          privateKey: |
                       -----BEGIN EC PRIVATE KEY-----
                       MHcCAQEEIGJyJBr+S5r6p6BqsksGI475GkRhDyDNrji7C0eBzvsIoAoGCCqGSM49
                       AwEHoUQDQgAElm1JTpwbwsGLJ1/u1WTCxqHfO/IuP7uKEydvumgsRckgKw5mjp1k
                       +xdSsji2ORlpSA1bM1WuRtR2Gk8y8LlElw==
                       -----END EC PRIVATE KEY-----
        encrypt:
          enabled: false