server:
  port: 9000
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adithyamr/personal-investment-tracker-config.git
          default-label: main
          clone-on-start: true
          force-pull: true
          search-paths:
          - '*api'
        encrypt:
          enabled: false